FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
RUN apt-get update && apt-get install -y nodejs
COPY ["FirstDemo/*.csproj", "FirstDemo/"]
COPY ["FirstDemo.Data/*.csproj", "FirstDemo.Data/"]
COPY ["FirstDemo.Common/*.csproj", "FirstDemo.Common/"]
COPY ["FirstDemo.Membership/*.csproj", "FirstDemo.Membership/"]
COPY ["FirstDemo.Training/*.csproj", "FirstDemo.Training/"]
RUN dotnet restore "FirstDemo/FirstDemo.csproj"
COPY . .
WORKDIR "/src/FirstDemo"
RUN dotnet build "FirstDemo.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "FirstDemo.csproj" -c Release -o /app

FROM build AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "FirstDemo.dll"]